global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:9000']
      metrics_path: '/metrics'
      scrape_interval: 10s